version: '3'

services:
###> doctrine/doctrine-bundle ###
   database:
    container_name: database
    image: mysql:${MYSQL_VERSION:-8.0.32}-debian
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # You should definitely change the password in production
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-StrongP4ssw0rd}
    volumes:
      - ./tmp/db/data:/var/lib/mysql
    restart: always
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
